name: Geant4 testing

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    extends:
      template: https://github.com/geant-val/geant-val-ci-workflows/blob/main/.github/workflows/geant-val-ci-workflows.yaml
